// Compatibility view: preserves legacy behavior until the audited model cutover.
export function mountCatalog(catalog, {document, now = () => Date.now(), schedule = setInterval, cancel = clearInterval} = {}) {
  if (!document) throw new TypeError('document is required');
  const SOURCE_DATA = catalog;
  const CHRONO_ORDER = catalog.chrono_order;
const rank=Object.fromEntries(CHRONO_ORDER.map((x,i)=>[x,i]));
const UNIVERSE_LABELS={sacred:'神圣时间线','earth-828':'Earth-828',xmen:'变种人宇宙',branch:'分支',tva:'分支'};
function formatInUniverse(value){if(!value||!value.start)return '时间未定/时间之外';const start=String(value.start),end=value.end==null?'':String(value.end);if(end&&end!==start){if(/^\d{4}$/.test(start)&&/^\d{4}$/.test(end))return start+'–'+end+'年';return start+'–'+end}return /^\d{4}$/.test(start)?start+'年':start}
function formatWorkType(x){if(x.type==='film')return '电影';if(x.episodes===1)return '特别篇';return x.episodes?'剧集（'+x.episodes+'集）':'剧集'}
function formatSaga(value){return value==='Infinity Saga'?'无限传奇':'多元宇宙传奇'}
const DATA=SOURCE_DATA.works.map((x,i)=>({
  ...x,idx:i,zh:x.title_cn,en:x.title,format:formatWorkType(x),sagaLabel:formatSaga(x.saga),release:x.release_date||'日期待定',
  desc:x.synopsis_cn,chars:x.key_characters||[],line:UNIVERSE_LABELS[x.universe]||'分支',typeKey:x.type==='film'?'电影':'剧集',
  releaseKey:x.release_date||'9999-12-31',chrono:rank[x.id]??999,upcoming:x.status==='upcoming',time:formatInUniverse(x.in_universe),
  note:x.in_universe&&x.in_universe.note?x.in_universe.note:''
}));
const state={sort:'chrono',phase:'all',saga:'all',line:'all',type:'all',q:''};
function eraFor(x){if(state.sort==='release')return{key:'p'+x.phase,title:'PHASE '+x.phase,sub:x.phase<=3?'无限传奇':'多元宇宙传奇'};const n=x.chrono;if(n<=4)return{key:'origin',title:'起源与旧世界',sub:'公元前 1260 — 1998'};if(n<=17)return{key:'heroes',title:'英雄纪元',sub:'2008 — 2015'};if(n<=32)return{key:'war',title:'分裂与终局',sub:'2016 — 2023'};if(n<=57)return{key:'multiverse',title:'多元宇宙开启',sub:'2024 — 2026'};return{key:'collision',title:'三界汇流',sub:'2027 → 待揭晓'}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderCard(x){const phaseLabel=x.en.startsWith("X-Men '97")?`P${x.phase} · 非官方`:`PHASE ${x.phase}`;return `<article class="card" data-line="${esc(x.line)}"><div class="meta"><span class="badge phase">${phaseLabel}</span><span class="badge">${esc(x.format)}</span><span class="badge line">${esc(x.line)}</span>${x.upcoming?'<span class="badge status">待上映</span>':''}</div><h3>${esc(x.zh)}</h3><p class="en">${esc(x.en)}</p><div class="dates"><div class="datecell"><span>宇宙内时间点</span><b>${esc(x.time)}</b></div><div class="datecell"><span>${x.upcoming?'计划上线 / 上映':'首映 / 上线'}</span><b>${esc(x.release)}</b></div></div><p class="desc">${esc(x.desc)}</p><div class="cast">${x.chars.slice(0,6).map(c=>`<span>${esc(c)}</span>`).join('')}</div>${x.note?`<div class="note">${esc(x.note)}</div>`:''}</article>`}
function render(){const q=state.q.trim().toLowerCase();let rows=DATA.filter(x=>(state.phase==='all'||String(x.phase)===state.phase)&&(state.saga==='all'||x.sagaLabel===state.saga)&&(state.line==='all'||x.line===state.line)&&(state.type==='all'||x.typeKey===state.type)&&(!q||[x.zh,x.en,x.desc,x.time,x.chars.join(' ')].join(' ').toLowerCase().includes(q)));rows.sort(state.sort==='chrono'?(a,b)=>a.chrono-b.chrono:(a,b)=>a.releaseKey.localeCompare(b.releaseKey)||a.idx-b.idx);document.getElementById('result-count').textContent=`显示 ${rows.length} / ${DATA.length} 部作品`;document.getElementById('view-title').textContent=state.sort==='chrono'?'宇宙内编年史':'上映顺序';const el=document.getElementById('timeline');if(!rows.length){el.innerHTML='<div class="empty"><h3>没有匹配作品</h3><p>试试清除搜索词或调整筛选条件。</p></div>';return}const groups=[];rows.forEach(x=>{const g=eraFor(x);let last=groups[groups.length-1];if(!last||last.key!==g.key){last={...g,items:[]};groups.push(last)}last.items.push(x)});el.innerHTML=groups.map(g=>`<section class="group"><header class="group-label"><b>${g.title}</b><span>${g.sub}</span></header><div class="cards">${g.items.map(renderCard).join('')}</div></section>`).join('')}
document.querySelectorAll('[data-sort]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-sort]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.sort=btn.dataset.sort;render()}));document.querySelectorAll('[data-filter]').forEach(group=>group.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;group.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state[group.dataset.filter]=b.dataset.value;render()}));document.getElementById('search').addEventListener('input',e=>{state.q=e.target.value;render()});document.getElementById('clear').addEventListener('click',()=>{Object.assign(state,{sort:state.sort,phase:'all',saga:'all',line:'all',type:'all',q:''});document.getElementById('search').value='';document.querySelectorAll('[data-filter]').forEach(g=>{g.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===0))});render()});
function getCountdownTarget(){const timestamp=now();return DATA.filter(x=>x.upcoming&&x.type==='film'&&/^\d{4}-\d{2}-\d{2}$/.test(x.release_date||'')).map(x=>({...x,targetTime:new Date(x.release_date+'T00:00:00').getTime()})).filter(x=>x.targetTime>timestamp).sort((a,b)=>a.targetTime-b.targetTime)[0]||null}
function tick(){const panel=document.getElementById('countdown'),target=getCountdownTarget();if(!target){panel.hidden=true;return}panel.hidden=false;document.getElementById('countdown-name').textContent='《'+target.zh+'》';document.getElementById('countdown-en').textContent=target.en.toUpperCase();document.getElementById('countdown-date').textContent=target.release_date.split('-').join(' · ');const diff=target.targetTime-now();const d=Math.floor(diff/864e5),h=Math.floor(diff/36e5)%24,m=Math.floor(diff/6e4)%60,s=Math.floor(diff/1e3)%60;['days','hours','mins','secs'].forEach((id,i)=>document.getElementById(id).textContent=String([d,h,m,s][i]).padStart(2,'0'))}
tick();const timer=schedule(tick,1000);document.getElementById('total-stat').textContent=DATA.length;render();

  return () => cancel(timer);
}
